---
title: "Calculate repeatability for each allele of the human mtDNA (takes 2 days)"
author: "Konstantin Popadin"
date: "29/07/2025"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls(all=TRUE))
library(knitr)
# library(tidyverse)  # install.packages("tidyverse")
# library(kableExtra)
library(dplyr)
library(tidyr)
library(ggplot2)
library(Biostrings) # install.packages("Biostrings")
library(stringdist) # install.packages("stringdist")
library(IRanges)

source("/home/popa/Repeatability/scripts/functions/RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence.R")

#install.packages(
#  "BiocManager",
#  repos = "https://cloud.r-project.org"
#)
#BiocManager::install("Biostrings")
```
## Background
<br>
<br><br>

## 1. Run it for several model mutations

***
```{r}
# get fasta from here: https://www.ncbi.nlm.nih.gov/nuccore/NC_012920.1?report=fasta and save it to data/1_raw/Homo_sapients.mtDNA.fasta

mtDNA <- readDNAStringSet("../data/1_raw/Homo_sapients.mtDNA.fasta")
mtDNA_seq <- mtDNA[[1]]
length(mtDNA_seq)
output_folder = "/home/popa/Repeatability/data/2_derived/01KP"

RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8251,"T",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8251,"A",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8251,"G",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8251,"C",output_folder) # other parameters keep by default

RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8472,"T",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8472,"A",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8472,"G",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8472,"C",output_folder) # other parameters keep by default

RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8473,"T",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8473,"A",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8473,"G",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,8473,"C",output_folder) # other parameters keep by default

RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,12705,"T",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,12705,"A",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,12705,"G",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,12705,"C",output_folder) # other parameters keep by default

RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,14798,"T",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,14798,"A",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,14798,"G",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,14798,"C",output_folder) # other parameters keep by default

RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,16223,"T",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,16223,"A",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,16223,"G",output_folder) # other parameters keep by default
RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq,16223,"C",output_folder) # other parameters keep by default

```
<br>
<br><br>

# 2 RUN for All positions and all nucleotides 

```{r}
mtDNA <- readDNAStringSet("../data/1_raw/Homo_sapients.mtDNA.fasta")
mtDNA_seq <- mtDNA[[1]]
length(mtDNA_seq)
seq_length <- length(mtDNA_seq)
output_folder = "/home/popa/Repeatability/data/2_derived/01KP"
nucleotides <- c("A", "T", "G", "C")

total_tasks <- seq_length * length(nucleotides)
task_counter <- 0
start_time <- Sys.time()

# Loop over each position in the sequence
for (pos in 1:seq_length) {   # Loop over each nucleotide 
  for (fixed_nuc in nucleotides) {
    task_counter <- task_counter + 1
    # Calculate percent done
    percent_done <- (task_counter / total_tasks) * 100
    
    # Timing
    elapsed <- Sys.time() - start_time
    
    # Print progress message
    cat(sprintf("Processing position: %d, nucleotide: %s (%.2f%% done), elapsed time: %s\r",
                pos, fixed_nuc, percent_done, format(elapsed, digits=4)))
    flush.console()
    
    # Call the repeat finding function
    RetrieveAllRepeatsCoveringGivenPositionAndNucleotideInSequence(mtDNA_seq, pos, fixed_nuc, output_folder)
  }
}

cat("\nAll processing complete. Total time:", format(Sys.time() - start_time), "\n")
```

<br>
<br><br>

# 3 tar gzip groups of txt files to make several <45Mb archives for GitHub

```{r}

# Split a directory into gzip-compressed tar archives below the target size.
# Original files are not deleted or modified.

create_tar_parts <- function(source_dir, output_dir,
                             target_mib = 300, # with this threshold each archive is < 50 Mb which is good for GitHub
                             archive_prefix = "repeatability_data") {
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  target_bytes <- target_mib * 1024^2
  tar_overhead_per_file <- 1024

  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(source_dir)

  # Collect files and estimate their archive size.
  files <- list.files(".", recursive = TRUE, all.files = TRUE,
                      include.dirs = FALSE)
  sizes <- file.info(files)$size
  estimated_sizes <- sizes + tar_overhead_per_file

  # Divide files into groups below the target size.
  groups <- list()
  current_files <- character()
  current_size <- 0

  for (i in seq_along(files)) {
    if (length(current_files) > 0 &&
        current_size + estimated_sizes[i] > target_bytes) {
      groups[[length(groups) + 1]] <- current_files
      current_files <- character()
      current_size <- 0
    }

    current_files <- c(current_files, files[i])
    current_size <- current_size + estimated_sizes[i]
  }

  if (length(current_files) > 0)
    groups[[length(groups) + 1]] <- current_files

  # Create the archives.
  for (i in seq_along(groups)) {
    archive_path <- file.path(
      output_dir,
      sprintf("%s_%03d.tar.gz", archive_prefix, i)
    )

    utils::tar(
      tarfile = archive_path,
      files = groups[[i]],
      compression = "gzip",
      tar = "internal"
    )

    message(sprintf(
      "Created %s: %.2f MiB",
      basename(archive_path),
      file.size(archive_path) / 1024^2
    ))
  }

  invisible(groups)
}

# Example:
create_tar_parts(
  source_dir = "/home/popa/Repeatability/data/2_derived/01KP",
  output_dir = "/home/popa/Repeatability/data/2_derived/01KP.ARCHIVE",
  target_mib = 300
)

```


<br>
<br><br>

# 4 before pushing to GitHub remove by hand all txt files from /home/popa/Repeatability/data/2_derived/01KP

```{r}
```