---
title: "Calculate and compare repeatability for Ref and ALt alleles of the model mutations"
author: "Konstantin Popadin"
date: "29/07/2025"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls(all=TRUE))
library(knitr)
library(tidyverse)
library(kableExtra)
library(dplyr)
library(tidyr)
library(ggplot2)
library(Biostrings)
library(stringdist) # install.packages("stringdist")
library(IRanges)

```
## Background
<br>
<br><br>

## 1. 

***
```{r}
major_arc_start <- 5798
major_arc_end <- 16568

rep = read.table("../data/2_derived/01KP/01KP.8473.T.txt", header = TRUE)

filtered_rep <- rep[
  !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
  (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
  (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end) &   # repeat in major arc
  (rep$repeat.hamming.distance == 0) &                                        # perfect similarity
  (rep$motif.start < rep$pos & rep$pos < rep$motif.end),                      # pos strictly inside motif
]

filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
View(filtered_rep[1,])

rep = read.table("../data/2_derived/01KP/01KP.8473.C.txt", header = TRUE)
filtered_rep <- rep[
  !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
  (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
  (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end) &   # repeat in major arc
  (rep$repeat.hamming.distance == 0) &                                        # perfect similarity
  (rep$motif.start < rep$pos & rep$pos < rep$motif.end),                      # pos strictly inside motif
]

filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
View(filtered_rep[1,])


rep = read.table("../data/2_derived/01KP/01KP.8251.G.txt", header = TRUE)
filtered_rep <- rep[
  !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
  (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
  (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end) &   # repeat in major arc
  (rep$repeat.hamming.distance == 0) &                                        # perfect similarity
  (rep$motif.start < rep$pos & rep$pos < rep$motif.end),                      # pos strictly inside motif
]
filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
View(filtered_rep[1,])

rep = read.table("../data/2_derived/01KP/01KP.8251.A.txt", header = TRUE)
filtered_rep <- rep[
  !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
  (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
  (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end) &   # repeat in major arc
  (rep$repeat.hamming.distance == 0) &                                        # perfect similarity
  (rep$motif.start < rep$pos & rep$pos < rep$motif.end),                      # pos strictly inside motif
]
filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
View(filtered_rep[1,])

rep = read.table("../data/2_derived/01KP/01KP.14798.T.txt", header = TRUE)
filtered_rep <- rep[
  !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
  (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
  (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end)   # repeat in major arc
  # & (rep$repeat.hamming.distance == 0)                                         # perfect similarity
  #& (rep$motif.start < rep$pos & rep$pos < rep$motif.end)                      # pos strictly inside motif
  ,]
filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
View(filtered_rep[1,]) # 13

rep = read.table("../data/2_derived/01KP/01KP.14798.C.txt", header = TRUE)
filtered_rep <- rep[
  !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
  (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
  (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end)    # repeat in major arc
  # & (rep$repeat.hamming.distance == 0)                                         # perfect similarity
  # & (rep$motif.start < rep$pos & rep$pos < rep$motif.end)                      # pos strictly inside motif
  ,]
filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
View(filtered_rep[1,]) # 17

```
<br>
<br><br>

## 2. make function and run it

```{r}

RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge <- function(pos, nuc) {
  # Define major arc boundaries
  major_arc_start <- 5798
  major_arc_end <- 16568
  
  # Construct file path
  file_path <- paste0("../data/2_derived/01KP/01KP.", pos, ".", nuc, ".txt")
  
  # Read the file
  rep <- read.table(file_path, header = TRUE)
  
  # Apply filters
  filtered_rep <- rep[
    !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
    (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
    (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end) &   # repeat in major arc
    (rep$repeat.hamming.distance == 0) &                                        # perfect similarity
    (rep$motif.start < rep$pos & rep$pos < rep$motif.end),                      # pos strictly inside motif
  ]
  
  # Sort by effective.length (descending)
  filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
  
  # Return motif.length of the first row (if any)
  if (nrow(filtered_rep) > 0) {
    return(filtered_rep$motif.length[1])
  } else {
    return(NA)  # or return 0, or any default value if no rows match
  }
}


Repeatability10DegradedLongestInsideMajorArcPosNotAtTheEdge <- function(pos, nuc) {
  # Define major arc boundaries
  major_arc_start <- 5798
  major_arc_end <- 16568
  
  # Construct file path
  file_path <- paste0("../data/2_derived/01KP/01KP.", pos, ".", nuc, ".txt")
  
  # Read the file
  rep <- read.table(file_path, header = TRUE)
  
  # Calculate degradation percentage
  rep$degradation <- ((rep$motif.length - rep$effective.length) / rep$motif.length) * 100
  
  # Apply filters
  filtered_rep <- rep[
    !(rep$motif.start == rep$repeat.start & rep$motif.end == rep$repeat.end) &  # motif != repeat
    (rep$motif.start >= major_arc_start & rep$motif.end <= major_arc_end) &     # motif in major arc
    (rep$repeat.start >= major_arc_start & rep$repeat.end <= major_arc_end) &   # repeat in major arc
    (rep$motif.start < rep$pos & rep$pos < rep$motif.end) &                     # pos strictly inside motif
    (rep$degradation <= 10),                                                    # degradation <= 10%
  ]
  
  # Sort by effective.length (descending)
  filtered_rep <- filtered_rep[order(filtered_rep$effective.length, decreasing = TRUE), ]
  
  # Return motif.length of the first row (if any)
  if (nrow(filtered_rep) > 0) {
    return(filtered_rep$motif.length[1])
  } else {
    return(NA)  # or return 0, or any default value if no rows match
  }
}

### test model mutations: 3 SYN + Control region are the most important. The rest is suggestive (just to discuss in the paper)
## 8251G>A SYN THE SAME LENGTH BUT ALT IS ASSOCIATED WITH SIGNIFICANTLY DECREASED GC CONTENT, so DECREASED !!!!
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(8251,'G')
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(8251,'A')
## 8472C>T DECREASED !!!!!!
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(8472,'C')
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(8472,'T')
## 8473T>C SYN DECREASED !!!!!!
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(8473,'T')
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(8473,'C')
## 12705C>T SYN INCREASED !!!!!
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(12705,'C')
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(12705,'T')
## 14798T>C THE SAME LENGTH (if degraded => INCREASED) 
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(14798,'T')
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(14798,'C')
## 16223C>T DECREASED !!!!!
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(16223,'C')
RepeatabilityPerfectLongestInsideMajorArcPosNotAtTheEdge(16223,'T')

```
